#!/bin/sh

module=tuxedo-wmi
version=x.x.x

set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [  "`dkms status -m $module`" ]
       	then
            dkms remove -m $module -v $version --all
            rmmod -s tuxedo_wmi || true
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0


